task:
  - url: "https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/refs/heads/main/output/converted.txt"
    tag: "Surfboard"
  - url: "https://raw.githubusercontent.com/roosterkid/openproxylist/refs/heads/main/V2RAY.txt"
    tag: "RoosterKid"

settings:
  test_dl: true               # 启用节点测速
  test_streaming: true        # 检测 Netflix/YouTube 解锁情况
  sort_by_speed: true         # 节点测速后排序
  export_format: "clash"      # 输出 Clash 格式订阅
  rename_node: true           # 自动重命名节点（含地区/延迟等）
  output_dir: "output"        # 输出目录
